# Generated by Django 5.0.13 on 2025-04-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='projection',
            name='desired_grade',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='actual_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='projected_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='projection',
            name='desired_gpa',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projection',
            name='is_on_track',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cumulative_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='student',
            name='total_credit_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='projection',
            name='current_gpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='projection',
            name='required_final_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='gpa.major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.major'),
        ),
    ]
