# Generated by Django 5.0.13 on 2025-04-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0002_major_remove_projection_desired_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='actual_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='projected_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='year',
        ),
    ]
